### ISSUE TITLE
TextureAtlas demo should use KtxAsync instead of Gdx Timer

### ISSUE THREAD

**Issue by DavidPartouche** [DavidPartouche/ktx-samples#1]
@czyzby 
I've been struggling to make this part of the code work with Ktx:
[TextureAtlasDemo.kt](https://github.com/DavidPartouche/ktx-samples/blob/master/4-texture-atlas-demo/core/src/main/kotlin/io/github/davidpartouche/textureatlasdemo/TextureAtlasDemo.kt)
```
        ktxAsync {
            asynchronous {
                interval(0f, 1 / 30f) {
                    currentFrame++
                    if (currentFrame > 20)
                        currentFrame = 1

                    currentAtlasKey = currentFrame.toString().padStart(4, '0')
                    sprite.setRegion(textureAtlas.findRegion(currentAtlasKey))
                }
            }
        }
```
I must use KtxAsync in a wrong way, because it looks like the code is executed on the main thread...

**Comment by czyzby** [comment]
You're mixing LibGDX wrappers and KTX coroutines. As far as I remember, `interval` calls LibGDX `Timer`, which executes the code on the main thread. If you wanted to rewrite that into asynchronous code, you should replace that callback with a simple loop:

```kotlin
while(true) {
    asynchronous { doStuff() }
    delay(1f / 30f)
}
```

You can also try switching `interval` and `ktxAsync`/`asynchronous`, but that might defeat the purpose of using coroutines altogether.
